describe("calculator", () => {
  beforeEach(() => {
    cy.visit("/")
  })

  it("correctly handles calculations", () => {
    cy.clickCalculatorButton("4")
      .clickCalculatorButton("4")
      .get(".primary-operand")
      .should("have.text", "44")
      .clickCalculatorButton("+")
      .get('.history > [data-operation=""]')
      .should("have.text", "+")
      .get(".primary-operand")
      .should("have.text", "0")
      .get(".secondary-operand")
      .should("have.text", "44")
      .clickCalculatorButton("6")
      .get(".primary-operand")
      .should("have.text", "6")
      .clickCalculatorButton("=")
      .get(".primary-operand")
      .should("have.text", "50")
      .get('.history > [data-operation=""]')
      .should("have.text", "")
      .get(".secondary-operand")
      .should("have.text", "")
  })

  it("correctly handles all clear", () => {
    cy.visit("/")
      .clickCalculatorButton("4")
      .clickCalculatorButton("+")
      .clickCalculatorButton("6")
      .clickCalculatorButton("AC")
      .get(".primary-operand")
      .should("have.text", "0")
      .get('.history > [data-operation=""]')
      .should("have.text", "")
      .get(".secondary-operand")
      .should("have.text", "")
  })

  it("correctly handles delete", () => {
    cy.visit("/")
      .clickCalculatorButton("4")
      .clickCalculatorButton("DEL")
      .get(".primary-operand")
      .should("have.text", "0")
  })
})
